Support tsx/jsx files in svelte-check
When using --watch with svelte-check, saving a tsx/jsx files would cause
this error:

```
.../dev/svelte-language-tools/packages/svelte-check/test/typedrendering.tsx:4:3
Error: The keyword 'let' is reserved (svelte)
export function tsxFunction() {
  let b: number = 3;
  b = '1234';

.../dev/svelte-language-tools/packages/svelte-check/test/typedrendering.tsx:4:3
Error: The keyword 'let' is reserved (js)
export function tsxFunction() {
  let b: number = 3;
  b = '1234';
```

Which necessitated the change in language-server.